version: '2'
services:
  mongoose:
    image: mongooseim/mongooseim
    container_name: "mongoose"
    hostname: "mongoose-1"
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - '5222:5222' # client port
      - '8088:8088' # admin API
      - '8089:8089' # client API
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./config:/member
  db:
    image: mysql:5.7
    container_name: "monngoose-mysql"
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: "mongoose"
    ports:
      - '3306:3306'
    volumes:
        - "~/var/mysql/mongoose:/var/lib/mysql"
        - "./initdb:/docker-entrypoint-initdb.d"
